### ISSUE TITLE
FACIL services

### ISSUE THREAD

**Issue by millette** [CoSocial-Canada/FediverseGalaxies#1]
FACIL, a Québec non-profit promoting free software and open source, shares a bunch of services:

<https://facil.services/>

**Comment by bmann** [comment]
@millette thank you! I have added it. Still working on the schema, I see you have a wiki as well, and lots of local co-ops to keep track of in Quebec.

**Comment by millette** [comment]
I was involved with FACiL a long time ago, along with @obicke (whom I think you know). You can reach out to them directly if needs be: <https://facil.qc.ca/form_contact>.
